exp_name: trial_2
folder: Experiments
num_epochs: 30
lr: 0.001
optim: Adam
num_classes: 20
img_size: 512
seed: 16
batch_size: 4
use_gpu: False
kaggle: False
mac: True
resume: True
step_train: 0
step_val: 0

b1_seg_loss_weight: 1
seg_loss_weight: 1
cos_loss_weight: 1

threshold: 0.5

text_encoder:
  freeze: True
  pretrained: ViT-B-16.pt
  context_length: 77
  vocab_size: 49408
  transformer_width: 512
  transformer_layers: 12
  transformer_heads: 8
  embed_dim: 512

Resnet:
  model_type: RN50
  freeze: True
  pretrained: RN50.pt
  layers: [3, 4, 6, 3]
  output_dim: 1024
  heads: 8
  width: 64

VIT:
  model_type: ViT-B/16
  freeze: True
  pretrained: ViT-B-16.pt
  patch_size: 16
  width: 768
  layers: 12
  heads: 12
  output_dim: 512
  drop_path_rate: 0.1
  out_indices: [11]
  get_embeddings: True

SegDecoder:
  in_channels: 512
  embed_dim: 512
  num_layers: 3
  num_heads: 8
  use_stages: 1
  use_proj: True

Decoder:
  output_resolution: 512
  bilinear: True
